version: '2.1'
services:
  nginx:
    image: adrianacto/acto-nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  php:
    image: adrianacto/acto-php:latest
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  worker:
    image: adrianacto/acto-worker:latest
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
    ports:
     - "6379:6379"
  elasticsearch:
    image: elastic/elasticsearch:6.3.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - appnet
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - data:/var/lib/mysql
    networks:
     - appnet
    ports:
     - "3306:3306"
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
  esdata:
    driver: "local"
